using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;

namespace OasisEditor.Views;

public partial class InputMapView : UserControl
{
    private bool _commitNotificationPending;

    public InputMapView()
    {
        InitializeComponent();
    }

    private void InputMapGrid_OnCellEditEnding(object? sender, DataGridCellEditEndingEventArgs e)
    {
        if (e.EditAction != DataGridEditAction.Commit)
        {
            return;
        }

        // Focus may not have moved yet (for example when a toolbar command is clicked), so push
        // the editing control into the model before allowing the grid to complete its commit.
        UpdateEditingElementSource(e.EditingElement);

        // CellEditEnding is raised before the grid has finished committing the row. Queue the
        // persistence callback so both commits have completed, and coalesce events generated by
        // CommitEdit itself.
        _commitNotificationPending = true;
        Dispatcher.BeginInvoke(DispatcherPriority.DataBind, new Action(CommitPendingInputMapEdit));
    }

    private static void UpdateEditingElementSource(FrameworkElement editingElement)
    {
        switch (editingElement)
        {
            case TextBox textBox:
                textBox.GetBindingExpression(TextBox.TextProperty)?.UpdateSource();
                break;
            case ToggleButton toggleButton:
                toggleButton.GetBindingExpression(ToggleButton.IsCheckedProperty)?.UpdateSource();
                break;
            case ComboBox comboBox:
                comboBox.GetBindingExpression(Selector.SelectedValueProperty)?.UpdateSource();
                comboBox.GetBindingExpression(Selector.SelectedItemProperty)?.UpdateSource();
                comboBox.GetBindingExpression(ComboBox.TextProperty)?.UpdateSource();
                break;
        }
    }

    private void InputMapGrid_OnUnloaded(object sender, RoutedEventArgs e)
    {
        // A queued dispatcher callback may not run when the pane or application is closing.
        // Flush it synchronously while the view still has its DataContext.
        _commitNotificationPending = true;
        CommitPendingInputMapEdit();
    }

    private void CommitPendingInputMapEdit()
    {
        if (!_commitNotificationPending)
        {
            return;
        }

        if (!InputMapGrid.CommitEdit(DataGridEditingUnit.Cell, true) ||
            !InputMapGrid.CommitEdit(DataGridEditingUnit.Row, true))
        {
            return;
        }

        _commitNotificationPending = false;
        if (DataContext is MainWindowViewModel viewModel)
        {
            viewModel.NotifyInputDefinitionChanged();
        }
    }

    private void InputMapGrid_OnPreviewKeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.A && Keyboard.Modifiers == ModifierKeys.Control)
        {
            InputMapGrid.SelectAll();
            e.Handled = true;
            return;
        }

        if (e.Key == Key.Delete && Keyboard.Modifiers == ModifierKeys.None)
        {
            DeleteSelectedRows();
            e.Handled = true;
        }
    }

    private void InputMapGrid_OnPreviewMouseRightButtonDown(object sender, MouseButtonEventArgs e)
    {
        var row = FindVisualParent<DataGridRow>(e.OriginalSource as DependencyObject);
        if (row is null || row.IsSelected)
        {
            return;
        }

        InputMapGrid.SelectedItems.Clear();
        row.IsSelected = true;
        InputMapGrid.CurrentItem = row.Item;
    }

    private void InputMapContextMenu_OnOpened(object sender, RoutedEventArgs e)
    {
        DeleteMenuItem.IsEnabled = InputMapGrid.SelectedItems.Count > 0;
    }

    private void DeleteMenuItem_OnClick(object sender, RoutedEventArgs e) => DeleteSelectedRows();

    private void DeleteSelectedRows()
    {
        if (DataContext is not MainWindowViewModel viewModel)
        {
            return;
        }

        var selectedInputs = InputMapGrid.SelectedItems.OfType<InputDefinitionModel>().ToArray();
        if (selectedInputs.Length == 0)
        {
            return;
        }

        // InputDefinitions is intentionally the project's List-backed model rather than an
        // ObservableCollection. Detach DataGrid selection from those items before mutating the
        // list, then explicitly refresh the view so its cached rows and indexes cannot go stale.
        InputMapGrid.SelectedItems.Clear();
        InputMapGrid.CurrentItem = null;

        if (viewModel.DeleteInputDefinitions(selectedInputs) > 0)
        {
            InputMapGrid.Items.Refresh();
        }
    }

    private static T? FindVisualParent<T>(DependencyObject? child) where T : DependencyObject
    {
        while (child is not null)
        {
            if (child is T parent)
            {
                return parent;
            }

            child = VisualTreeHelper.GetParent(child);
        }

        return null;
    }
}
