namespace MfmeFmlDecoder.Model  // Or whatever namespace you want the registry in
{
    public enum MFMEComponentType
    {
        BaseClass = 0x00,
        Background = 0x01,
        Reel = 0x03,
        Lamp = 0x04,
        Button = 0x05,
        DiscReel = 0x06,
        Alpha = 0x07,
        BandReel = 0x08,
        Frame = 0x09,
        Label = 0x0A,
        Bitmap = 0x0B,
        BFMAlpha = 0x0C,
        DotMatrix = 0x0D,
        SevenSeg = 0x0E,
        BarcrestBWBVideo = 0x0F,
        AceMatrix = 0x10,
        ProconnMatrix = 0x11,
        Led = 0x12,
        DotAlpha = 0x13,
        Checkbox = 0x14,
        BFMLED = 0x15,
        EpochDotAlpha = 0x16,
        AlphaNew = 0x19,
        MatrixAlpha = 0x1A,
        Border = 0x1B,
        SevenSegBlock = 0x1C,
        BFMVideo = 0x1F,
        IGTVfd = 0x20,
        AceVideo = 0x21,
        EpochMatrix = 0x22,
        PlasmaDisplay = 0x23,
        BFMColourLed = 0x24,
        RGBLed = 0x26,
        ReelBonusReel = 0x27,
        MaygayVideo = 0x28,
        PrismLamp = 0x29,
        AstraMatrix = 0x2C,
        FlipReel = 0x2D,
        MaygayMatrix = 0x2E,
        CoinmasterVideo = 0x2F
    }
}