using System.Runtime.InteropServices;
using System.Text;

namespace OasisEditor;

internal sealed unsafe class FabricMachineSession : IFabricMachineSession
{
    private const int MaxLamps=4096,MaxReels=64,MaxCharacters=64,MaxSegments=256; private readonly FabricNativeExports _e; private readonly Action _released; private nint _handle; private bool _shutdown;
    internal FabricMachineSession(nint handle,FabricNativeExports exports,Action released){_handle=handle;_e=exports;_released=released;var n=new FabricCapabilitiesNative{Size=(uint)sizeof(FabricCapabilitiesNative),Version=FabricAbi.Version};Check(_e.GetCapabilitiesFn(_handle,&n),"FabricSessionGetCapabilities");Capabilities=new(n.Flags);}
    public FabricCapabilities Capabilities{get;}
    public void Initialise()=>Check(_e.Initialise(_handle),"FabricSessionInitialise"); public void Reset()=>Check(_e.Reset(_handle),"FabricSessionReset");
    public void Advance(TimeSpan elapsed){if(elapsed<TimeSpan.Zero)throw new ArgumentOutOfRangeException(nameof(elapsed));Check(_e.AdvanceFn(_handle,checked((ulong)(elapsed.Ticks*100))),"FabricSessionAdvance");}
    public void SubmitInput(FabricInput input){var n=new FabricInputNative{Size=(uint)sizeof(FabricInputNative),Version=FabricAbi.Version,Index=input.NumericalIndex,Active=input.Active?(byte)1:(byte)0};fixed(byte* p=n.Identifier)FabricRuntimeLibrary.WriteFixed(input.Identifier,p,64);Check(_e.SubmitInputFn(_handle,&n),"FabricSessionSubmitInput");}
    public FabricAudioFormat GetAudioFormat(){var n=new FabricAudioFormatNative{Size=(uint)sizeof(FabricAudioFormatNative),Version=FabricAbi.Version};Check(_e.GetAudioFormatFn(_handle,&n),"FabricSessionGetAudioFormat");return new(n.SampleRate,n.Channels,n.BitsPerSample,n.Interleaved!=0,n.Signed!=0,n.LittleEndian!=0);}
    public int ReadAudio(Span<short> samples,int frameCapacity){if(frameCapacity<0)throw new ArgumentOutOfRangeException(nameof(frameCapacity));fixed(short* p=samples){Check(_e.ReadAudioFn(_handle,p,(uint)frameCapacity,out var written),"FabricSessionReadAudio");if(written>(uint)frameCapacity)throw new InvalidDataException("Fabric returned more audio frames than requested.");return (int)written;}}
    public FabricMachineSnapshot GetSnapshot(){uint lc=0,rc=0,cc=0,sc=0;for(var attempt=0;attempt<3;attempt++){var lamps=new FabricLampNative[lc];var reels=new FabricReelNative[rc];var chars=new FabricCharacterDisplayNative[cc];var segments=new FabricSegmentDisplayNative[sc];fixed(FabricLampNative* lp=lamps)fixed(FabricReelNative* rp=reels)fixed(FabricCharacterDisplayNative* cp=chars)fixed(FabricSegmentDisplayNative* sp=segments){var n=new FabricMachineSnapshotNative{Size=(uint)sizeof(FabricMachineSnapshotNative),Version=FabricAbi.Version,Lamps=(nint)lp,LampCapacity=lc,Reels=(nint)rp,ReelCapacity=rc,Characters=(nint)cp,CharacterCapacity=cc,Segments=(nint)sp,SegmentCapacity=sc};var result=_e.GetSnapshotFn(_handle,&n);if(result==FabricResult.BufferTooSmall){Guard(n.LampCount,MaxLamps,"lamps");Guard(n.ReelCount,MaxReels,"reels");Guard(n.CharacterCount,MaxCharacters,"character displays");Guard(n.SegmentCount,MaxSegments,"segment displays");lc=n.LampCount;rc=n.ReelCount;cc=n.CharacterCount;sc=n.SegmentCount;continue;}Check(result,"FabricSessionGetSnapshot");return Convert(n,lamps,reels,chars,segments);}}throw new InvalidDataException("Fabric snapshot capacities did not stabilise after three attempts.");}
    private static FabricMachineSnapshot Convert(FabricMachineSnapshotNative n,FabricLampNative[] lamps,FabricReelNative[] reels,FabricCharacterDisplayNative[] chars,FabricSegmentDisplayNative[] segments){var ml=new List<FabricLamp>((int)n.LampCount);for(var i=0;i<n.LampCount;i++){fixed(byte* p=lamps[i].Identifier)ml.Add(new(Read(p,64),lamps[i].Index,lamps[i].LogicalState!=0,lamps[i].Brightness));}var mr=new List<FabricReel>((int)n.ReelCount);for(var i=0;i<n.ReelCount;i++){fixed(byte* p=reels[i].Identifier)mr.Add(new(Read(p,64),reels[i].Index,reels[i].Position));}var mc=new List<FabricCharacterDisplay>((int)n.CharacterCount);for(var i=0;i<n.CharacterCount;i++){if(chars[i].Count>16)throw new InvalidDataException("Fabric character count exceeds 16.");var values=new uint[chars[i].Count];var attrs=new byte[chars[i].Count];fixed(uint* p=chars[i].Characters)new ReadOnlySpan<uint>(p,values.Length).CopyTo(values);fixed(byte* p=chars[i].Attributes)new ReadOnlySpan<byte>(p,attrs.Length).CopyTo(attrs);fixed(byte* p=chars[i].Identifier)mc.Add(new(Read(p,64),values,attrs));}var ms=new List<FabricSegmentDisplay>((int)n.SegmentCount);for(var i=0;i<n.SegmentCount;i++){if(segments[i].Count>16)throw new InvalidDataException("Fabric digit count exceeds 16.");var masks=new ulong[segments[i].Count];fixed(ulong* p=segments[i].Masks)new ReadOnlySpan<ulong>(p,masks.Length).CopyTo(masks);fixed(byte* p=segments[i].Identifier)ms.Add(new(Read(p,64),masks));}return new(n.Sequence,ml,mr,mc,ms);}
    private static string Read(byte* p,int cap){var s=new ReadOnlySpan<byte>(p,cap);var z=s.IndexOf((byte)0);return Encoding.UTF8.GetString(z<0?s:s[..z]);} private static void Guard(uint count,int max,string kind){if(count>max)throw new InvalidDataException($"Fabric requested {count} {kind}; managed safety limit is {max}.");}
    private void Check(FabricResult result,string op){if(result!=FabricResult.Ok)throw FabricRuntimeLibrary.Error(result,op,_handle,true,_e);}
    public void Shutdown(){if(_handle==0||_shutdown)return;Check(_e.Shutdown(_handle),"FabricSessionShutdown");_shutdown=true;}
    public void Dispose(){if(_handle==0)return;try{if(!_shutdown)Shutdown();}catch{}finally{try{_e.DestroySessionFn(_handle);}catch{} _handle=0;_released();}GC.SuppressFinalize(this);}~FabricMachineSession(){Dispose();}
}
