using System.Collections.Concurrent;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace OasisEditor;

public sealed class FabricEmulationBackend : IEmulationBackend
{
    private readonly string _runtimePath,_amberPath; private readonly Func<string,IFabricRuntimeLibrary> _factory; private readonly IEmulationAudioSink _audio; private readonly ConcurrentQueue<(int,bool)> _inputs=new(); private readonly HashSet<int> _asserted=[]; private readonly Dictionary<int,(bool,float)> _lamps=[]; private readonly Dictionary<int,int> _reels=[]; private readonly Dictionary<int,ulong> _segments=[];
    private IFabricRuntimeLibrary? _runtime;private IFabricMachineSession? _session;private CancellationTokenSource? _cts;private Task? _pump;private long _baseline;private bool _shutdown,_disposed;private FabricAudioFormat? _format;private short[] _audioBuffer=[];
    public FabricEmulationBackend(string runtimePath,string amberPath):this(runtimePath,amberPath,p=>new FabricRuntimeLibrary(p),new NAudioEmulationAudioSink()){}
    internal FabricEmulationBackend(string runtimePath,string amberPath,Func<string,IFabricRuntimeLibrary> factory,IEmulationAudioSink audio){_runtimePath=runtimePath;_amberPath=amberPath;_factory=factory;_audio=audio;}
    public EmulationBackendKind BackendKind=>EmulationBackendKind.NativeSystem6; public EmulationBackendState State{get;private set;}=EmulationBackendState.Stopped;public EmulationBackendCapabilities Capabilities{get;}=new(true,true,true,true,false,false,false,false);
    public event EventHandler<EmulationBackendState>? StateChanged;public event EventHandler<MachineLampChangedEventArgs>? LampChanged;public event EventHandler<MachineReelChangedEventArgs>? ReelChanged;public event EventHandler<MachineSegmentChangedEventArgs>? SegmentChanged;public event EventHandler<MachineVfdBrightnessChangedEventArgs>? VfdBrightnessChanged;public event EventHandler<MachineDotMatrixChangedEventArgs>? DotMatrixChanged{add{}remove{}}
    public Task StartAsync(EmulationLaunchRequest request,CancellationToken ct){ct.ThrowIfCancellationRequested();Set(EmulationBackendState.Starting);try{var s=request.System6NativeRoms??throw new InvalidOperationException("Fabric System 6 requires native ROM settings.");var resources=Resources(s).ToArray();_runtime=_factory(_runtimePath);_session=_runtime.CreateSession(new("amber-api-v2","jpm-system6",_amberPath,resources,FabricAmberConfiguration.FromSystem6(s)));_session.Initialise();if(_session.Capabilities.Has(FabricCapability.Audio)){var f=_session.GetAudioFormat();if(f is not {SampleRate:48000,ChannelCount:2,BitsPerSample:16,Interleaved:true,SignedSamples:true,LittleEndian:true})throw new NotSupportedException($"Unsupported Fabric audio format: {f}.");_format=f;_audioBuffer=new short[96];_audio.Start(new(48000,2,16));}_shutdown=false;_baseline=Stopwatch.GetTimestamp();_cts=CancellationTokenSource.CreateLinkedTokenSource(ct);_pump=Task.Run(()=>Pump(_cts.Token),CancellationToken.None);Set(EmulationBackendState.Running);return Task.CompletedTask;}catch{CleanupFailure();Set(EmulationBackendState.Failed);throw;}}
    private static IEnumerable<FabricRomResource> Resources(System6NativeRomSettings s){uint i=0;foreach(var p in s.ProgramRomPaths.TakeWhile(x=>!string.IsNullOrWhiteSpace(x)))yield return new(FabricRomRole.Program,i++,p);i=0;foreach(var p in s.SoundRomPaths.TakeWhile(x=>!string.IsNullOrWhiteSpace(x)))yield return new(FabricRomRole.Sound,i++,p);}
    private async Task Pump(CancellationToken ct){try{while(!ct.IsCancellationRequested){if(State!=EmulationBackendState.Running){await Task.Delay(1,ct);_baseline=Stopwatch.GetTimestamp();continue;}var now=Stopwatch.GetTimestamp();var delta=now-_baseline;_baseline=now;_session!.Advance(TimeSpan.FromSeconds((double)delta/Stopwatch.Frequency));while(_inputs.TryDequeue(out var x)){_session.SubmitInput(new($"oasis.switch.{x.Item1}",x.Item1,x.Item2));if(x.Item2)_asserted.Add(x.Item1);else _asserted.Remove(x.Item1);}Publish(_session.GetSnapshot());if(_format is { } f){var frames=_session.ReadAudio(_audioBuffer,_audioBuffer.Length/f.ChannelCount);var bytes=MemoryMarshal.AsBytes(_audioBuffer.AsSpan(0,frames*f.ChannelCount));if(!bytes.IsEmpty)_audio.PushPcm(bytes);}await Task.Delay(1,ct);}}catch(OperationCanceledException)when(ct.IsCancellationRequested){}catch{Set(EmulationBackendState.Failed);}}
    private void Publish(FabricMachineSnapshot s){foreach(var x in s.Lamps)if(!_lamps.TryGetValue(x.NumericalIndex,out var old)||old!=(x.LogicalState,x.Brightness)){_lamps[x.NumericalIndex]=(x.LogicalState,x.Brightness);LampChanged?.Invoke(this,new(x.NumericalIndex,x.LogicalState?Math.Max(1,(int)Math.Round(x.Brightness*255)):0));}foreach(var x in s.Reels)if(!_reels.TryGetValue(x.NumericalIndex,out var old)||old!=x.Position){_reels[x.NumericalIndex]=x.Position;ReelChanged?.Invoke(this,new(x.NumericalIndex,x.Position));}foreach(var d in s.CharacterDisplays)for(var i=0;i<d.Characters.Length;i++){var mask=(ulong)d.Characters[i]|((ulong)d.Attributes[i]<<32);if(!_segments.TryGetValue(i,out var old)||old!=mask){_segments[i]=mask;SegmentChanged?.Invoke(this,new(i,unchecked((int)d.Characters[i]),MameSegmentOutputType.NativeAlpha));}}foreach(var d in s.SegmentDisplays)for(var i=0;i<d.SegmentMasks.Length;i++)if(!_segments.TryGetValue(i,out var old)||old!=d.SegmentMasks[i]){_segments[i]=d.SegmentMasks[i];SegmentChanged?.Invoke(this,new(i,unchecked((int)d.SegmentMasks[i]),MameSegmentOutputType.Digit));}}
    public Task SetInputStateAsync(InputDefinitionModel d,bool pressed,CancellationToken ct){ct.ThrowIfCancellationRequested();if(_session?.Capabilities.Has(FabricCapability.DigitalInput)!=true)throw new NotSupportedException("Fabric session does not support digital input.");if(!int.TryParse(d.ButtonNumber,out var i))throw new InvalidOperationException($"Input '{d.Id}' has no numeric switch mapping.");_inputs.Enqueue((i,pressed));return Task.CompletedTask;}
    public Task PauseAsync(CancellationToken ct){ct.ThrowIfCancellationRequested();if(State==EmulationBackendState.Running)Set(EmulationBackendState.Paused);return Task.CompletedTask;}public Task ResumeAsync(CancellationToken ct){ct.ThrowIfCancellationRequested();if(State==EmulationBackendState.Paused){_baseline=Stopwatch.GetTimestamp();Set(EmulationBackendState.Running);}return Task.CompletedTask;}
    public Task ResetAsync(EmulationResetKind kind,CancellationToken ct){ct.ThrowIfCancellationRequested();Release();_session?.Reset();_baseline=Stopwatch.GetTimestamp();_lamps.Clear();_reels.Clear();_segments.Clear();_audio.Clear();return Task.CompletedTask;}
    private void Release(){if(_session is not null)foreach(var i in _asserted)_session.SubmitInput(new($"oasis.switch.{i}",i,false));_asserted.Clear();while(_inputs.TryDequeue(out _)){} }
    public async Task StopAsync(CancellationToken ct){if(State==EmulationBackendState.Stopped)return;Set(EmulationBackendState.Stopping);if(_cts is not null)await _cts.CancelAsync();if(_pump is not null)try{await _pump.WaitAsync(ct);}catch(OperationCanceledException)when(_cts.IsCancellationRequested){}Release();if(_session is not null&&!_shutdown){_session.Shutdown();_shutdown=true;}_audio.Stop();_session?.Dispose();_runtime?.Dispose();_session=null;_runtime=null;_cts?.Dispose();_cts=null;_pump=null;Set(EmulationBackendState.Stopped);}
    private void CleanupFailure(){try{_session?.Dispose();}finally{_runtime?.Dispose();_session=null;_runtime=null;_audio.Stop();}}
    public async ValueTask DisposeAsync(){if(_disposed)return;await StopAsync(CancellationToken.None);_audio.Dispose();_disposed=true;}private void Set(EmulationBackendState s){State=s;StateChanged?.Invoke(this,s);}
}
