// Registers all GameConfig maps. Regenerated by tools/GenGameConfigMaps.

using MfmeFmlDecoder.GameConfig.Maps;

namespace MfmeFmlDecoder.GameConfig
{
    internal static class GameConfigMapRegistration
    {
        public static void RegisterAll()
        {
            GameConfigMapRegistry.Register(ACEVIDEOGameConfigMap.SystemName, ACEVIDEOGameConfigMap.Create);
            GameConfigMapRegistry.Register(ADDER5GameConfigMap.SystemName, ADDER5GameConfigMap.Create);
            GameConfigMapRegistry.Register(ASTRASYSA1GameConfigMap.SystemName, ASTRASYSA1GameConfigMap.Create);
            GameConfigMapRegistry.Register(BLACKBOXGameConfigMap.SystemName, BLACKBOXGameConfigMap.Create);
            GameConfigMapRegistry.Register(ELECTROCOINGameConfigMap.SystemName, ELECTROCOINGameConfigMap.Create);
            GameConfigMapRegistry.Register(EPOCHGameConfigMap.SystemName, EPOCHGameConfigMap.Create);
            GameConfigMapRegistry.Register(IGTSPlusGameConfigMap.SystemName, IGTSPlusGameConfigMap.Create);
            GameConfigMapRegistry.Register(IMPACTGameConfigMap.SystemName, IMPACTGameConfigMap.Create);
            GameConfigMapRegistry.Register(M1ABGameConfigMap.SystemName, M1ABGameConfigMap.Create);
            GameConfigMapRegistry.Register(M1VIDEOGameConfigMap.SystemName, M1VIDEOGameConfigMap.Create);
            GameConfigMapRegistry.Register(MACH2000AGameConfigMap.SystemName, MACH2000AGameConfigMap.Create);
            GameConfigMapRegistry.Register(MACH2000EGameConfigMap.SystemName, MACH2000EGameConfigMap.Create);
            GameConfigMapRegistry.Register(MMMGameConfigMap.SystemName, MMMGameConfigMap.Create);
            GameConfigMapRegistry.Register(MPS2GameConfigMap.SystemName, MPS2GameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU2GameConfigMap.SystemName, MPU2GameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU3GameConfigMap.SystemName, MPU3GameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU4GameConfigMap.SystemName, MPU4GameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU4PLASMAGameConfigMap.SystemName, MPU4PLASMAGameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU4VIDEOGameConfigMap.SystemName, MPU4VIDEOGameConfigMap.Create);
            GameConfigMapRegistry.Register(MPU5GameConfigMap.SystemName, MPU5GameConfigMap.Create);
            GameConfigMapRegistry.Register(PHOENIXGameConfigMap.SystemName, PHOENIXGameConfigMap.Create);
            GameConfigMapRegistry.Register(PHOENIX2GameConfigMap.SystemName, PHOENIX2GameConfigMap.Create);
            GameConfigMapRegistry.Register(PLUTO5GameConfigMap.SystemName, PLUTO5GameConfigMap.Create);
            GameConfigMapRegistry.Register(PROCONNGameConfigMap.SystemName, PROCONNGameConfigMap.Create);
            GameConfigMapRegistry.Register(SCORPION1GameConfigMap.SystemName, SCORPION1GameConfigMap.Create);
            GameConfigMapRegistry.Register(SCORPION2GameConfigMap.SystemName, SCORPION2GameConfigMap.Create);
            GameConfigMapRegistry.Register(SCORPION4GameConfigMap.SystemName, SCORPION4GameConfigMap.Create);
            GameConfigMapRegistry.Register(SCORPION5GameConfigMap.SystemName, SCORPION5GameConfigMap.Create);
            GameConfigMapRegistry.Register(SpACEGameConfigMap.SystemName, SpACEGameConfigMap.Create);
            GameConfigMapRegistry.Register(SRUGameConfigMap.SystemName, SRUGameConfigMap.Create);
            GameConfigMapRegistry.Register(SYS1GameConfigMap.SystemName, SYS1GameConfigMap.Create);
            GameConfigMapRegistry.Register(SYS5GameConfigMap.SystemName, SYS5GameConfigMap.Create);
            GameConfigMapRegistry.Register(SYS83GameConfigMap.SystemName, SYS83GameConfigMap.Create);
            GameConfigMapRegistry.Register(SYS85GameConfigMap.SystemName, SYS85GameConfigMap.Create);
            GameConfigMapRegistry.Register(SYSTEM80GameConfigMap.SystemName, SYSTEM80GameConfigMap.Create);
        }
    }
}
