using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using System.IO;
using Microsoft.Win32;
using OasisEditor.Features.CabinetEditor.Models;
using OasisEditor.Features.CabinetEditor.Services;

namespace OasisEditor.Features.CabinetEditor.ViewModels;

public sealed class CabinetReflectionEditorViewModel : INotifyPropertyChanged
{
    private readonly DocumentTabViewModel _document; private readonly Func<IReadOnlyList<DocumentTabViewModel>>? _documents; private CabinetReflectionDefinition? _selected;
    public CabinetReflectionEditorViewModel(DocumentTabViewModel document, Func<IReadOnlyList<DocumentTabViewModel>>? documents)
    {
        _document = document; _documents = documents; AddCommand = new RelayCommand(Add, () => Targets.Count > 0); RemoveCommand = new RelayCommand(Remove, () => Selected is not null); DuplicateCommand = new RelayCommand(Duplicate, () => Selected is not null); DeriveCommand = new RelayCommand(Derive, () => Selected is not null); BrowseMaskCommand = new RelayCommand(BrowseMask, () => Selected is not null); ClearMaskCommand = new RelayCommand(() => Mask = string.Empty, () => Selected is not null); Refresh();
    }
    public event PropertyChangedEventHandler? PropertyChanged;
    public ObservableCollection<CabinetReflectionDefinition> Items { get; } = new(); public ObservableCollection<CabinetReflectionReceiverTarget> Targets { get; } = new(); public ObservableCollection<string> FaceIds { get; } = new(); public ObservableCollection<CabinetFaceTarget> FaceTargets { get; } = new();
    public ICommand AddCommand { get; } public ICommand RemoveCommand { get; } public ICommand DuplicateCommand { get; } public ICommand DeriveCommand { get; }
    public ICommand BrowseMaskCommand { get; } public ICommand ClearMaskCommand { get; }
    public IReadOnlyList<string> Presets { get; } = new[] { CabinetReflectionPreset.RoughPlastic, CabinetReflectionPreset.PolishedChrome, CabinetReflectionPreset.Custom }; public IReadOnlyList<string> PlaneSources { get; } = new[] { CabinetReflectionPlaneSource.Automatic, CabinetReflectionPlaneSource.Manual };
    public CabinetReflectionDefinition? Selected { get => _selected; set { _selected = value; RaiseAll(); } }
    public bool HasSelection => Selected is not null;
    public string Id { get => Selected?.Id ?? string.Empty; set => Update(item => item with { Id = value }); }
    public bool Enabled { get => Selected?.Settings.Enabled ?? false; set => UpdateSettings(settings => settings with { Enabled = value }); }
    public CabinetReflectionReceiverTarget? Target { get => Targets.FirstOrDefault(item => item.TargetPath == Selected?.TargetId); set { if (value is not null) Update(item => item with { TargetId = value.TargetPath, MaterialSlot = 0 }); } }
    public IReadOnlyList<CabinetReflectionMaterialSlot> Slots => Target?.MaterialSlots ?? Array.Empty<CabinetReflectionMaterialSlot>();
    public CabinetReflectionMaterialSlot? Slot { get => Slots.FirstOrDefault(item => item.Index == Selected?.MaterialSlot); set { if (value is not null) Update(item => item with { MaterialSlot = value.Index }); } }
    public string FaceId { get => Selected?.SourceFaceId ?? string.Empty; set => Update(item => item with { SourceFaceId = value }); }
    public string Preset { get => Selected is null ? CabinetReflectionPreset.Custom : CabinetReflectionPreset.Detect(Selected.Settings); set => UpdateSettings(settings => CabinetReflectionPreset.Resolve(value, settings)); }
    public string PlaneSource { get => Selected?.PlaneSource ?? CabinetReflectionPlaneSource.Automatic; set => Update(item => item with { PlaneSource = value }); }
    public string Mask { get => Selected?.VisibilityMask ?? string.Empty; set => Update(item => item with { VisibilityMask = string.IsNullOrWhiteSpace(value) ? null : value.Trim() }); }
    public double Strength { get => Selected?.Settings.Strength ?? 0; set => UpdateSettings(settings => settings with { Strength = value }); } public double Artwork { get => Selected?.Settings.UnlitArtworkStrength ?? 0; set => UpdateSettings(settings => settings with { UnlitArtworkStrength = value }); } public double Lamps { get => Selected?.Settings.LitLampStrength ?? 0; set => UpdateSettings(settings => settings with { LitLampStrength = value }); } public double Roughness { get => Selected?.Settings.Roughness ?? 0; set => UpdateSettings(settings => settings with { Roughness = value }); } public double Distortion { get => Selected?.Settings.Distortion ?? 0; set => UpdateSettings(settings => settings with { Distortion = value }); }
    public double FresnelStrength { get => Selected?.Settings.FresnelStrength ?? 0; set => UpdateSettings(settings => settings with { FresnelStrength = value }); } public double FresnelPower { get => Selected?.Settings.FresnelPower ?? 0; set => UpdateSettings(settings => settings with { FresnelPower = value }); } public double EdgeFade { get => Selected?.Settings.EdgeFade ?? 0; set => UpdateSettings(settings => settings with { EdgeFade = value }); }
    public double OriginX { get => Selected?.Plane.Origin.X ?? 0; set => UpdatePlane(plane => plane with { Origin = plane.Origin with { X = value } }); } public double OriginY { get => Selected?.Plane.Origin.Y ?? 0; set => UpdatePlane(plane => plane with { Origin = plane.Origin with { Y = value } }); } public double OriginZ { get => Selected?.Plane.Origin.Z ?? 0; set => UpdatePlane(plane => plane with { Origin = plane.Origin with { Z = value } }); }
    public double RightX { get => Selected?.Plane.Right.X ?? 0; set => UpdatePlane(plane => plane with { Right = plane.Right with { X = value } }); } public double RightY { get => Selected?.Plane.Right.Y ?? 0; set => UpdatePlane(plane => plane with { Right = plane.Right with { Y = value } }); } public double RightZ { get => Selected?.Plane.Right.Z ?? 0; set => UpdatePlane(plane => plane with { Right = plane.Right with { Z = value } }); }
    public double UpX { get => Selected?.Plane.Up.X ?? 0; set => UpdatePlane(plane => plane with { Up = plane.Up with { X = value } }); } public double UpY { get => Selected?.Plane.Up.Y ?? 0; set => UpdatePlane(plane => plane with { Up = plane.Up with { Y = value } }); } public double UpZ { get => Selected?.Plane.Up.Z ?? 0; set => UpdatePlane(plane => plane with { Up = plane.Up with { Z = value } }); } public double Width { get => Selected?.Plane.Width ?? 0; set => UpdatePlane(plane => plane with { Width = value }); } public double Height { get => Selected?.Plane.Height ?? 0; set => UpdatePlane(plane => plane with { Height = value }); }
    public string Validation { get { if (Selected is null) return string.Empty; if (Items.Count(item => item.Id == Selected.Id) > 1) return "Duplicate receiver ID."; if (Target is null) return "Cabinet renderer is missing."; if (Slot is null) return "Material slot is invalid."; if (!FaceIds.Contains(FaceId)) return "Source Face is missing."; return CabinetReflectionPlaneValidation.TryValidate(Selected.Plane, out var error) ? "Valid" : error; } }
    public void SetDiscovery(IEnumerable<CabinetReflectionReceiverTarget> targets, IEnumerable<CabinetFaceTarget> faceTargets) { Targets.Clear(); foreach (var item in targets) Targets.Add(item); FaceTargets.Clear(); foreach (var item in faceTargets) FaceTargets.Add(item); (AddCommand as RelayCommand)?.RaiseCanExecuteChanged(); RaiseAll(); }
    public void Refresh() { var id = Selected?.Id; Items.Clear(); foreach (var item in _document.GetCabinetDocument().Reflections ?? []) Items.Add(item); FaceIds.Clear(); if (_documents is not null) foreach (var faceId in _documents().Where(item => item.Document.DocumentType == EditorDocumentType.Face).Select(item => item.GetFaceDocument().Id).Where(item => !string.IsNullOrWhiteSpace(item)).Distinct()) FaceIds.Add(faceId); Selected = Items.FirstOrDefault(item => item.Id == id) ?? Items.FirstOrDefault(); }
    private void Add() { var target = Targets.FirstOrDefault(); if (target is null) return; var item = new CabinetReflectionDefinition("reflection-" + Guid.NewGuid().ToString("N"), target.TargetPath, 0, FaceIds.FirstOrDefault() ?? string.Empty, new(new(0, 0, 0), new(1, 0, 0), new(0, 1, 0), 1, 1), CabinetReflectionSettings.RoughPlastic); _document.CommandService.Execute(CabinetMutationCommands.CreateAddReflectionCommand(_document.DocumentId, _document, item)); Refresh(); Selected = Items.First(candidate => candidate.Id == item.Id); Derive(); }
    private void Remove() { if (Selected is null) return; _document.CommandService.Execute(CabinetMutationCommands.CreateDeleteReflectionCommand(_document.DocumentId, _document, Selected.Id)); Refresh(); }
    private void Duplicate() { if (Selected is null) return; var copy = Selected with { Id = "reflection-" + Guid.NewGuid().ToString("N") }; _document.CommandService.Execute(CabinetMutationCommands.CreateAddReflectionCommand(_document.DocumentId, _document, copy)); Refresh(); Selected = Items.First(item => item.Id == copy.Id); }
    private void Derive() { if (Selected is null || _documents is null) return; var face = _documents().Where(item => item.Document.DocumentType == EditorDocumentType.Face).Select(item => item.GetFaceDocument()).FirstOrDefault(item => item.Id == Selected.SourceFaceId); var target = face is null ? null : FaceTargets.FirstOrDefault(item => item.Id == face.AssignedCabinetFaceTargetId); if (CabinetReflectionPlaneDeriver.TryDerive(target, out var plane, out _)) Update(item => item with { Plane = plane, PlaneSource = CabinetReflectionPlaneSource.Automatic }); }
    private void BrowseMask() { var dialog = new OpenFileDialog { Filter = "Image files|*.png;*.jpg;*.jpeg|All files|*.*" }; if (dialog.ShowDialog() != true) return; var cabinetDirectory = Path.GetDirectoryName(_document.Document.FilePath) ?? string.Empty; Mask = Path.GetRelativePath(cabinetDirectory, dialog.FileName).Replace('\\', '/'); }
    private void UpdateSettings(Func<CabinetReflectionSettings, CabinetReflectionSettings> update) => Update(item => item with { Settings = update(item.Settings).Normalized() });
    private void UpdatePlane(Func<CabinetReflectionPlane, CabinetReflectionPlane> update) => Update(item => item with { Plane = update(item.Plane), PlaneSource = CabinetReflectionPlaneSource.Manual });
    private void Update(Func<CabinetReflectionDefinition, CabinetReflectionDefinition> update) { if (Selected is null) return; var oldId = Selected.Id; var changed = update(Selected); _document.CommandService.Execute(CabinetMutationCommands.CreateUpdateReflectionCommand(_document.DocumentId, _document, oldId, changed)); Selected = changed; Refresh(); }
    private void RaiseAll([CallerMemberName] string? unused = null) { foreach (var name in new[] { nameof(Selected), nameof(HasSelection), nameof(Id), nameof(Enabled), nameof(Target), nameof(Slots), nameof(Slot), nameof(FaceId), nameof(Preset), nameof(PlaneSource), nameof(Mask), nameof(Strength), nameof(Artwork), nameof(Lamps), nameof(Roughness), nameof(Distortion), nameof(FresnelStrength), nameof(FresnelPower), nameof(EdgeFade), nameof(OriginX), nameof(OriginY), nameof(OriginZ), nameof(RightX), nameof(RightY), nameof(RightZ), nameof(UpX), nameof(UpY), nameof(UpZ), nameof(Width), nameof(Height), nameof(Validation) }) PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name)); foreach (var command in new[] { RemoveCommand, DuplicateCommand, DeriveCommand, BrowseMaskCommand, ClearMaskCommand }.OfType<RelayCommand>()) command.RaiseCanExecuteChanged(); }
}
